### ISSUE TITLE
Corrupted double-linked list

### ISSUE THREAD

**Issue by mader102** [mattiasflodin/reckless#11] opened 2016-11-18 22:26 UTC
Hi Mattias,

I build a benchmark to compare some Logger in Java, these are Log4J2, logback, spdlog, glog, g3log and reckless.

What I have seen, that spdlog, reckless and g3log are nearly insane, but g3log and reckless have some issues.

The issue I have is a corrupted double-linked list, my problem is, that I have no clou why and when this appears, but it appears sometimes.

*** Error in `java': corrupted double-linked list: 0x00007f56c4046530 ***

Therefore the results I gain from reckless are unusable, like g3log.
But in terms of speed it is similar to spdlog.

As I described, that I use Java I need to mention here, that I use JNI to load it into Java.
This is how I create the logger for reckless, maybe it can be done better:

using log_t = reckless::severity_log<
    reckless::indent<4>,       // 4 spaces of indent
    ' ',                       // Field separator
    reckless::severity_field,  // Show severity marker (D/I/W/E) first
    reckless::timestamp_field  // Then timestamp field
    >;
    
reckless::file_writer writer("logs/reckless_async.log");
log_t logger(&writer);

Cheers
Mader102

**Comment by mader102** [comment] 2016-11-22 18:08
In addition to this I also received a SIGSEGV
`#`
`# A fatal error has been detected by the Java Runtime Environment:`
`#`
`# SIGSEGV (0xb) at pc=0x00007f404238b4d4, pid=10051, tid=0x00007f400b3f3700`
`#`
`# JRE version: Java(TM) SE Runtime Environment (8.0_112-b15) (build 1.8.0_112-b15)`
`# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.112-b15 mixed mode linux-amd64 compressed oops)`
`# Problematic frame:`
`# C [libc.so.6+0x7a4d4]# [ timer expired, abort... ]`

**Comment by mattiasflodin** [comment] 2016-11-23 11:37
Hi Mader102,

Thanks I'll look into this, though it sounds like it may be difficult to reproduce the problem. Do you have the code for your benchmark available anywhere?

**Comment by mader102** [comment] 2016-11-27 19:03
Hi mattias,

I am little bit late for my thesis but it would be nice to find this out.

libreckless.cpp (need to be renamed because you renamed libasync.a to libreckless.a :)
`#include <string>
#include <jni.h>
#include <reckless/severity_log.hpp>
#include <reckless/file_writer.hpp>
#include "framework_JNI_RecklessJNI.h"

using namespace std;

using log_t = reckless::severity_log<
    reckless::indent<4>,       // 4 spaces of indent
    ' ',                       // Field separator
    reckless::severity_field,  // Show severity marker (D/I/W/E) first
    reckless::timestamp_field  // Then timestamp field
    >;

reckless::file_writer writer("logs/reckless_async.log");
log_t logger(&writer);

JNIEXPORT void JNICALL Java_framework_JNI_RecklessJNI_debug(JNIEnv *env, jobject thisObj, jstring _msg)
{
        string msg = env->GetStringUTFChars(_msg, NULL);
        logger.debug("%s", msg);
}

JNIEXPORT void JNICALL Java_framework_JNI_RecklessJNI_info(JNIEnv *env, jobject thisObj, jstring _msg)
{
        string msg = env->GetStringUTFChars(_msg, NULL);
        logger.info("%s", msg);
}

JNIEXPORT void JNICALL Java_framework_JNI_RecklessJNI_warn(JNIEnv *env, jobject thisObj, jstring _msg)
{
        string msg = env->GetStringUTFChars(_msg, NULL);
        logger.warn("%s", msg);
}

JNIEXPORT void JNICALL Java_framework_JNI_RecklessJNI_error(JNIEnv *env, jobject thisObj, jstring _msg)
{
        string msg = env->GetStringUTFChars(_msg, NULL);
        logger.error("%s", msg);
}
`
RecklessJNI.java is needed to import these C++ functions as native
`package framework.JNI;

public class RecklessJNI {
        static {
                System.loadLibrary("reckless");  
        }

        public native void debug(String _msg);
        public native void info(String _msg);
        public native void warn(String _msg);
        public native void error(String _msg);
}
`
you need to compile RecklessJNI.java, then use javah RecklessJNI
Use the created RecklessJNI.h for libreckless.cpp and compile this with your library libasync.a
g++ -std=c++11 -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -Iinclude -pthread -fpermissive -shared -Llib -fPIC src/libreckless.cpp -lasynclog -o lib/libreckless.so

then compile a main which uses new RecklessJNI() and use .warn(..) to call the library.

if youdo this in a loop which calls a thread of 1,2,4,8,16,32,64 and 128 threads then it will mostly fail at 128

I am logging 1024*1024 warn messages with threads and repeat this 10 times in a loop.

**Comment by mattiasflodin** [comment] 2019-01-03 11:49
I've been unable to reproduce this with current version of the code. If you are able to find a more reliable way of reproducing this (perhaps with a C++ test case?), please reopen the issue. But I'm closing it for now as I won't be able to do anything more.

**Closed as completed by mattiasflodin** 2019-01-03 11:49 UTC
Labels: wontfix
