### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by elvircrn** [mattiasflodin/reckless#17] opened 2018-11-22 13:27 UTC
I am interested in adding mac os support for this library as I have a macbook at hand. Is this project still being maintained?

**Comment by mattiasflodin** [comment] 2018-12-31 10:09
Hi, I'm still passionate about this project but I've found it very hard in the past year to set aside time for any kind of hobby work in my spare time (as you can obviously see from the long time it took to respond to this issue). However, if you do add Mac OS support then I'll be happy to merge it in.

If you decide to do it, I'd advise you to base your work on the wip/windows branch since it contains a serious redesign of many backend components, most importantly a new lockless queue for the log messages. Also, since this branch is a port to add Windows support, it's probably more appropriate as a base for a port to yet another OS. It's a work in progress and I'm likely going to squash a lot of commits, but if that causes any git conflicts I can help out with that.

The code itself isn't going to change much as it's mostly done. The reason it hasn't been released yet is that I have performance issues that I need to work out before release so I don't cause any regressions.

**Comment by elvircrn** [comment] 2019-01-05 22:46
Why did you decide to remove the CMakeLists file from that branch?

**Comment by mattiasflodin** [comment] 2019-01-06 08:07
On the contrary, the branch was made long before CMakeLists was added. It just wasn't merged yet. :)

Since the branch is a bit messy (but, hopefully soon, will be cleaned up and given a proper release) I would recommend that you focus on specific files that need porting, and implement them for OSX. For example, mpsc_ring_buffer.{hpp,cpp} and platform.{hpp,cpp}.

**Closed as completed** 2020-10-03 14:04 UTC
Labels: question
